### ISSUE TITLE
Node.js 16 actions are deprecated - github-action-composer.lock-diff@v2

### ISSUE THREAD

**Issue by MarcHagen** [WyriHaximus/github-action-composer.lock-diff#148]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6, actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Seems you have updated it in the `main` branch but not yet released a new version.
Do you have any progress on this?

**Comment by WyriHaximus** [comment]
Thanks for the nudge, new patch version should be released in a few minutes

**Comment by MarcHagen** [comment]
Thank very much! I’m don’t like to create these kinds of issues or nudges because sometimes there’s good reasons for not yet bumping versions.
I think you know exactly how I feel 😂. Anyway have a great day!

**Comment by WyriHaximus** [comment]
Fair, but non the less thanks for the nudge. Sometimes I just completely forget and realise a year later I should have tagged something. Have a great day as well :).
