### ISSUE TITLE
Incorrect HEAD resolution causing failure of ion-bazan/composer-diff (fatal: invalid object name)

### ISSUE THREAD

**Issue by janedbal** [WyriHaximus/github-action-composer.lock-diff#151]
See original report and comment from `ion-bazan/composer-diff` author: https://github.com/IonBazan/composer-diff/issues/30#issuecomment-1960683751

**Comment by WyriHaximus** [comment]
Thanks @janedbal having a look at how to solve this :+1:

**Comment by WyriHaximus** [comment]
@janedbal TL;DR upgrade to v2, the bug is in v1 and v2 is set up differently in such a way this issue doesn't exist. 

Did find some things that I'll address but nothing that relates to your specific issue.
