### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by njt1982** [WyriHaximus/github-action-composer.lock-diff#156]
Hi,

I see there was a similar issue in Feb (#148) and it looks like release 2.0.1 was pushed out soon after?

But I'm still getting this...
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6, actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

There is an automated PR (#142) for the github-script And I see that the checkout appears to already be on `@4` in the main branch, committed 8 months ago?

So not sure why I'm getting @v3 used...
![image](https://github.com/WyriHaximus/github-action-composer.lock-diff/assets/384976/35e57397-baf2-46b0-b578-7551c5383989)
Not sure why #135 doesn't seem to be in the 2.0.1 release notes?

**Comment by WyriHaximus** [comment]
Hey, #135 wasn't mentioned because I didn't add it to the milestone as I should have. Now the strange part for me is that looking at the `v2.0.1` release action file, it's all v4: https://github.com/WyriHaximus/github-action-composer.lock-diff/blob/20157a018749d1bc70e04e36f57bfff2281ed4f3/action.yaml let me dig deeper on why this is happening.

**Comment by WyriHaximus** [comment]
Ok found it, release workflow had an issue on update the v2 branch. Will look into this and fix it: https://github.com/WyriHaximus/github-action-composer.lock-diff/actions/runs/7805987710/job/21291444895

It's the first time I'm doing a hybrid composite and Docker action. Should have checked back then, will look into a fix tomorrow

**Comment by njt1982** [comment]
Thanks @WyriHaximus - much appreciated :) 

Hopefully it's a fix which won't consume too much of your Friday / Saturday :)

**Comment by WyriHaximus** [comment]
Took longer than intended, had to rework part of the release process, extracted it into a reusable workflow, still not fully happy with it but will address that outside this issue. Anyway, the Node 16 issue has now been resolved in [`v2.1.0`](https://github.com/WyriHaximus/github-action-composer.lock-diff/releases/tag/v2.1.0)
