### ISSUE TITLE
Keeps incorrectly reporting packages as changed

### ISSUE THREAD

**Issue by tannyl** [WyriHaximus/github-action-composer.lock-diff#71]
![image](https://user-images.githubusercontent.com/11209600/156741321-ff7651b1-6a90-4c80-b40c-1fe2eeb2a62b.png)
I keep getting false positives on two packages.

As you can see above the **roave/security-advisories** package reports as downgraded, even though `9999999-dev 77e3164` is exactly the same version as `dev-latest 77e3164`.

As for **friendsofsymfony/oauth-server-bundle** dev-master is a alias of 2.0.x-dev, so `2.0.x-dev 5940472` and `dev-master 5940472` are also exactly the same versions.

I guess the problem is not actually related to your code (after looking through it briefly) but more likely due to problems in the https://github.com/IonBazan/composer-diff plugin you are using.

**Comment by WyriHaximus** [comment]
Hey @tannyl it isn't even per se an issue with the underlying package used to generate the output. But how composer looks at them and considers them internally. I might be able to use markdown parsing and filter them out tbh.

**Comment by tannyl** [comment]
Thanks @WyriHaximus 
It is strange that composer ends up with two different names (for base and for target), considering the actual values in the compared lock files are the same?
But anyway, if you could filter messages like this, that would be great.

**Comment by ruudk** [comment]
While testing out the plugin I noticed the same problem. We rely on a few unreleased packages, and that makes the output unusable.

In this example, only the `nette/neon` package was bumped by Dependabot.
<img width="1010" alt="Screenshot 2022-03-22 at 08 40 38@2x" src="https://user-images.githubusercontent.com/104180/159431307-fe1e6258-6f1c-4387-bae6-272b047cd28e.png">

**Comment by WyriHaximus** [comment]
Started working on this in #74

**Comment by ruudk** [comment]
Thanks @WyriHaximus for working on this 💙

**Comment by WyriHaximus** [comment]
The filtering is working, making sure it now won't comment empty tables next before releasing the fix.

**Comment by WyriHaximus** [comment]
Confirmed the fix works, need to put in some work to confirm not commenting empty tables also works as intended before tagging a release.

**Comment by ruudk** [comment]
🚀 👏

**Comment by WyriHaximus** [comment]
:facepalm:  The bug turned out to be GitHub not always refreshing the UI because the comment gets deleted.

Just released [`v1.1.0`](https://github.com/WyriHaximus/github-action-composer.lock-diff/releases/tag/v1.1.0), and if you've been using this action with the `@v1` targeting you'll automatically get this release and fix.

**Comment by ruudk** [comment]
Thanks @WyriHaximus, we're gonna try it out 😊

**Comment by WyriHaximus** [comment]
Please let me know how it works for you @ruudk :+1:

**Comment by ruudk** [comment]
It works great, thanks so much!

**Comment by WyriHaximus** [comment]
Great to hear that @ruudk, and thank you for the confirmation 👍
