### ISSUE TITLE
Usage of deprectated `set-output`

### ISSUE THREAD

**Issue by pheller24** [WyriHaximus/github-action-composer.lock-diff#94]
Hey there,

thank you for this nice action.
I found a small warning in our pipeline and wanted to drop you a note :-)

![image](https://user-images.githubusercontent.com/86109056/209112494-9270c54e-7dd6-4f45-9e3f-a478cd008573.png)

> ... and plan to fully disable them on **31st May 2023**

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by WyriHaximus** [comment]
Hey @pheller24 Thanks for the heads up, been working on updating all my actions and this one was also on the list. Just filed https://github.com/WyriHaximus/github-action-composer.lock-diff/pull/96 to tackle this.

**Comment by WyriHaximus** [comment]
Just released [`v1.2.0`](https://github.com/WyriHaximus/github-action-composer.lock-diff/releases/tag/v1.2.0) with the fix for this in it
